version: "3.8"

services:
  client:
    build: ./client
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - api_handler
      - file_handler
    networks:
      - app_network

  api_handler:
    build: ./server/ApiHandler
    container_name: api_handler
    volumes:
      - /home/ec2-user/.aws/:/root/.aws/
    ports:
      - "5000:5000"
    networks:
      - app_network

  file_handler:
    build: ./server/FileHandler
    container_name: file_handler
    ports:
      - "5001:5001"
    networks:
      - app_network
    environment:
      - S3_BUCKET_NAME=${BUCKET_NAME}
      - AWS_REGION=${REGION}

networks:
  app_network:
    driver: bridge
