ROUTES = [
    "/users",
    "/isolated/users",
    "/dense/users",
    "/user/<string:user_id>",
    "/user/<string:user_id>/projects",
    "/user/<string:user_id>/collaborations",
    "/user/<string:user_id>/collaborators",
    "/projects",
    "/dense/projects",
    "/project/<string:project_id>",
    "/project/<string:project_id>/owner",
    "/project/<string:project_id>/classes",
    "/project/<string:project_id>/collaborators",
    "/shortest_path",
    "/all_paths",
    "/clusters",
    "/report"
]
