name: Test Deployment

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test-deployment:
    name: Build and Test Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Enable client to accept localhost
      run: |
        sed -i "s/{backend_ip}/localhost/g" client/script.js
    
    - name: Mock Environment Variables
      run: |
        BUCKET_NAME=mock-bucket
        REGION=us-east-1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Run Docker Compose
      run: |
        BUCKET_NAME=mock-bucket REGION=us-east-1 docker-compose up -d

    - name: Build and Start Containers
      run: |
        # Baja cualquier contenedor en ejecución
        docker-compose down --remove-orphans || true
        # Construye los servicios definidos en docker-compose.yml
        docker-compose build
        # Arranca los servicios en segundo plano
        BUCKET_NAME=mock-bucket REGION=us-east-1 docker-compose up -d
        # Muestra los logs (útil para depuración)
        docker-compose logs

    - name: Test API Endpoints
      run: |
        # Espera unos segundos para asegurarte de que los servicios estén listos
        sleep 60
        # Verifica la salud de la API del servidor
        curl -f http://localhost:5000/health || exit 1
        # Verifica la salud de la FILE API del servidor
        curl -f http://localhost:5001/health || exit 1

    - name: Stop and Clean Up
      run: docker-compose down --remove-orphans
